# Generated by Django 2.1.2 on 2018-11-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='products',
        ),
    ]
