# Generated by Django 2.1.2 on 2018-11-08 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_userds_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userds',
            name='user',
        ),
    ]
