# Generated by Django 2.1.2 on 2018-11-08 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('analytics', '0005_remove_userds_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggeredSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(max_length=120)),
                ('object_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
