# Generated by Django 2.1.2 on 2018-11-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_triggeredsignal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productds',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userds',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='ProductDS',
        ),
        migrations.DeleteModel(
            name='UserDS',
        ),
    ]
