# Generated by Django 2.1.2 on 2018-11-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DSs', '0002_auto_20181110_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productds',
            name='male',
        ),
        migrations.RemoveField(
            model_name='userds',
            name='male',
        ),
    ]
